"""
Layer L — Claim YAML Schema (schema_version: "1")

This module defines the ClaimRecord dataclass and associated parse/serialize
helpers for the `refs/aria/coordination` orphan-ref claim files.

Claim file path convention:
    claims/<container-id>/<session-id>.yaml        (active / yielded)
    archive/<YYYY-MM>/<container-id>/<session-id>-<claimed_at>.yaml  (done, GC'd)

Consumers:
    TASK-013  coordination_ref.py  — reads raw YAML dicts, calls parse_claim()
    TASK-015  reconcile.py         — reads ClaimRecord list, uses claimed_at / status
    TASK-018  claim_lifecycle.py   — calls serialize_claim() before write_claim()

Edge cases handled here (see docs/coordination-ref-schema.md §4):
    - schema_version missing       → parse_claim returns None
    - schema_version unknown       → parse_claim returns ClaimRecord(status="unknown")
    - required field missing       → parse_claim returns None
    - field type wrong             → parse_claim returns None
    - status not in STATUS_ENUM    → parse_claim returns None
    - claimed_at / heartbeat_at not valid ISO 8601 → parse_claim returns None
    - superseded_from malformed    → parse_claim returns None
    - corrupt YAML                 → caller (TASK-013) catches yaml.YAMLError before
                                     calling parse_claim; not handled here

status="unknown" in reconcile:
    Reconcile (TASK-015) SKIPS any ClaimRecord with status="unknown" entirely.
    It does not count as active, does not trigger collision detection, and does
    not affect verdicts for other claims on the same track_id.
    Rationale: unknown-version claim semantics may be incompatible with the
    current reconcile rules — skipping is the safety-first choice.
"""

from __future__ import annotations

import logging
from dataclasses import dataclass
from datetime import datetime
from typing import Optional

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

SCHEMA_VERSION_CURRENT: str = "1"

# STATUS_ENUM covers all values a ClaimRecord.status may hold at runtime.
# "unknown" is a reader-side sentinel — it is NEVER written by a live session.
# "abandoned" (coordination-claim-lifecycle-and-overlap Part C): terminal status
# written by release_claim*/gc.sweep_stale_active. reconcile/collision already
# treated it as terminal (forward-compat); before Part C the schema rejected it
# on parse, so a written abandoned claim silently vanished on read-back.
STATUS_ENUM: frozenset[str] = frozenset({"active", "yielded", "done", "abandoned", "unknown"})

# Values that a live session may write into the status field (excludes "unknown").
STATUS_WRITABLE: frozenset[str] = frozenset({"active", "yielded", "done", "abandoned"})

# Expected format for superseded_from: "owner/container/session"
_SUPERSEDED_FROM_PARTS = 3


# ---------------------------------------------------------------------------
# Data model
# ---------------------------------------------------------------------------

@dataclass(frozen=True)
class ClaimRecord:
    """Immutable representation of a parsed claim YAML file (schema_version=1).

    All datetime fields are stored as the original ISO 8601 strings from the
    YAML source so that callers can round-trip without precision loss.
    Downstream callers (reconcile.py) parse to datetime only when needed for
    comparison, using datetime.fromisoformat().

    Fields
    ------
    schema_version : str
        The version found in the raw dict. Always "1" for valid v1 claims.
        For unknown-version claims the actual value from the file is preserved
        so that operators can log it.
    track_id : str
        Deterministic work ID (normalized by TASK-014 lib/track_id.py::derive).
    owner : str
        git user.email local-part (everything before '@').
    container : str
        ~/.aria/container-id value (generated by TASK-011 lib/identity.py).
    session : str
        Ephemeral session identifier (short random + start timestamp).
    phase : str
        Ten-step-cycle phase at last write (e.g. "B.2", "D.3").
    status : str
        One of STATUS_ENUM. "unknown" is a reader-only sentinel for
        unrecognized schema versions — it is never written by a live session.
    claimed_at : str
        UTC ISO 8601 string (seconds precision). Immutable after initial write.
        Reconcile uses this for "earliest wins" rule.
    heartbeat_at : str
        UTC ISO 8601 string (seconds precision). Updated each heartbeat cycle
        (HEARTBEAT_INTERVAL = 600 s, defined in lib/constants.py by TASK-018)
        and on every phase transition.
    superseded_from : Optional[str]
        Present only during a reconcile take-over.
        Format: "owner/container/session" of the claim being superseded.
    linked_issue : Optional[str]
        Optional semantic-overlap signal (Part B1, coordination-claim-lifecycle-
        and-overlap): free-form issue reference (e.g. "10CG/Aria#160"). Two
        active claims with the SAME linked_issue but DIFFERENT track_id trigger
        an advisory overlap warning (collision.linked_issue_overlaps) — the
        "same issue, two names" collision that pure track_id string matching
        cannot see. Additive: absent in pre-B1 claims; never affects reconcile
        winner determination.
    """

    schema_version: str
    track_id: str
    owner: str
    container: str
    session: str
    phase: str
    status: str
    claimed_at: str
    heartbeat_at: str
    superseded_from: Optional[str] = None
    linked_issue: Optional[str] = None


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _soft_error(event: str, detail: str) -> None:
    """Emit a structured soft-error log (non-fatal).

    Future consumers (TASK-016 gate, TASK-017 board) may aggregate these.
    Using WARNING level so they surface in standard log output without raising.
    """
    logger.warning("claim_schema soft_error event=%s detail=%s", event, detail)


def _validate_iso8601(value: str, field: str) -> bool:
    """Return True if value is a parseable ISO 8601 datetime string."""
    try:
        datetime.fromisoformat(value.replace("Z", "+00:00"))
        return True
    except (ValueError, AttributeError):
        return False


def _validate_superseded_from(value: str) -> bool:
    """Return True if value matches 'owner/container/session' format (3 parts)."""
    parts = value.split("/")
    return len(parts) == _SUPERSEDED_FROM_PARTS and all(p.strip() for p in parts)


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

def parse_claim(raw: dict) -> Optional[ClaimRecord]:
    """Parse a raw dict (from YAML) into a ClaimRecord.

    Rules
    -----
    1. If ``schema_version`` is missing or not a string:
       return None + emit soft_error("claim_schema_invalid").

    2. If ``schema_version`` is present but != SCHEMA_VERSION_CURRENT:
       return a ClaimRecord with status="unknown" preserving the actual
       schema_version from the file. All other fields are filled with
       empty-string sentinels so the struct is valid Python. Reconcile
       will skip this record (safety-first, per §4.2 of schema doc).

    3. For schema_version == "1": validate all required fields. If any
       required field is missing, wrong type, or out of enum range:
       return None + emit soft_error("claim_schema_invalid").

    4. Optional ``superseded_from``: if present, validate format; if
       malformed, return None + emit soft_error("claim_schema_invalid").

    Corrupt YAML (yaml.YAMLError) is handled by the caller (TASK-013)
    before this function is invoked; it is not a concern here.

    Parameters
    ----------
    raw : dict
        The decoded YAML mapping from the claim file.

    Returns
    -------
    ClaimRecord | None
        ClaimRecord on success (including the status="unknown" sentinel case).
        None on any parse/validation failure.
    """
    # --- Step 1: extract and type-check schema_version ---
    schema_version = raw.get("schema_version")
    if schema_version is None:
        _soft_error(
            "claim_schema_invalid",
            "missing required field 'schema_version'",
        )
        return None
    if not isinstance(schema_version, str):
        _soft_error(
            "claim_schema_invalid",
            f"field 'schema_version' must be str, got {type(schema_version).__name__}",
        )
        return None

    # --- Step 2: unknown version → sentinel record, reconcile will skip ---
    if schema_version != SCHEMA_VERSION_CURRENT:
        _soft_error(
            "claim_schema_unknown_version",
            f"schema_version={schema_version!r} is not {SCHEMA_VERSION_CURRENT!r}; "
            "returning unknown-status sentinel; reconcile will skip this claim",
        )
        return ClaimRecord(
            schema_version=schema_version,
            track_id="",
            owner="",
            container="",
            session="",
            phase="",
            status="unknown",
            claimed_at="",
            heartbeat_at="",
            superseded_from=None,
        )

    # --- Step 3: validate all required v1 fields ---
    required_str_fields = [
        "track_id", "owner", "container", "session", "phase",
        "status", "claimed_at", "heartbeat_at",
    ]
    for field in required_str_fields:
        value = raw.get(field)
        if value is None:
            _soft_error(
                "claim_schema_invalid",
                f"missing required field '{field}'",
            )
            return None
        if not isinstance(value, str):
            _soft_error(
                "claim_schema_invalid",
                f"field '{field}' must be str, got {type(value).__name__}",
            )
            return None

    # status must be in the writable subset (live claims never write "unknown")
    status: str = raw["status"]
    if status not in STATUS_WRITABLE:
        _soft_error(
            "claim_schema_invalid",
            f"field 'status' value {status!r} not in writable STATUS_ENUM "
            f"{sorted(STATUS_WRITABLE)}",
        )
        return None

    # claimed_at and heartbeat_at must be valid ISO 8601
    for ts_field in ("claimed_at", "heartbeat_at"):
        if not _validate_iso8601(raw[ts_field], ts_field):
            _soft_error(
                "claim_schema_invalid",
                f"field '{ts_field}' is not valid ISO 8601: {raw[ts_field]!r}",
            )
            return None

    # --- Step 4: validate optional superseded_from ---
    superseded_from: Optional[str] = raw.get("superseded_from")
    if superseded_from is not None:
        if not isinstance(superseded_from, str):
            _soft_error(
                "claim_schema_invalid",
                f"field 'superseded_from' must be str, got {type(superseded_from).__name__}",
            )
            return None
        if not _validate_superseded_from(superseded_from):
            _soft_error(
                "claim_schema_invalid",
                f"field 'superseded_from' must be 'owner/container/session', "
                f"got {superseded_from!r}",
            )
            return None

    # --- Step 5: validate optional linked_issue (Part B1, additive) ---
    linked_issue: Optional[str] = raw.get("linked_issue")
    if linked_issue is not None and not isinstance(linked_issue, str):
        _soft_error(
            "claim_schema_invalid",
            f"field 'linked_issue' must be str, got {type(linked_issue).__name__}",
        )
        return None

    return ClaimRecord(
        schema_version=schema_version,
        track_id=raw["track_id"],
        owner=raw["owner"],
        container=raw["container"],
        session=raw["session"],
        phase=raw["phase"],
        status=status,
        claimed_at=raw["claimed_at"],
        heartbeat_at=raw["heartbeat_at"],
        superseded_from=superseded_from,
        linked_issue=linked_issue,
    )


def serialize_claim(record: ClaimRecord) -> dict:
    """Serialize a ClaimRecord back to a plain dict for YAML dumping.

    Used by TASK-013 ``write_claim()`` and TASK-018 ``heartbeat()`` /
    ``release()``.  Omits ``superseded_from`` if None (keeps YAML clean).

    Parameters
    ----------
    record : ClaimRecord
        A valid (non-unknown) ClaimRecord to serialize.

    Returns
    -------
    dict
        Ordered dict suitable for ``yaml.safe_dump()``.
        Fields are emitted in the canonical order defined by §2.1 of
        ``docs/coordination-ref-schema.md``.
    """
    out: dict = {
        "schema_version": record.schema_version,
        "track_id": record.track_id,
        "owner": record.owner,
        "container": record.container,
        "session": record.session,
        "phase": record.phase,
        "status": record.status,
        "claimed_at": record.claimed_at,
        "heartbeat_at": record.heartbeat_at,
    }
    if record.superseded_from is not None:
        out["superseded_from"] = record.superseded_from
    if record.linked_issue is not None:
        out["linked_issue"] = record.linked_issue
    return out
